import { Link } from 'react-router-dom';
import { Button } from '../components/ui/button.tsx';
import { Page, Panel, Metric, Status, Notice } from '../components/workspace/index.tsx';
import { useSimulation } from '../hooks/useWorkspace.tsx';

export function Overview() {
  const { applicant, receipts, dynamicScore, error } = useSimulation();
  return <Page eyebrow="Overview" title="Simulation overview" description="A transparent, synthetic underwriting decision-support workspace. Explore consent, evidence, behavior, fairness, and audit context without producing a real lending outcome."><div className="flex flex-wrap items-center justify-between gap-4"><div><Status band="strong">Simulation only</Status><p className="mt-2 text-sm text-muted">Session retention · server-owned state</p></div><Link to="/app/consent"><Button>Start a new simulation</Button></Link></div>{error && <Notice>{error}</Notice>}<div className="grid gap-4 sm:grid-cols-3"><Metric label="Applicant" value={applicant?.displayName ?? 'Awaiting consent'} detail={applicant?.applicantId ?? 'Synthetic fixture locked'} /><Metric label="Consent state" value={`${receipts.filter((receipt) => receipt.status === 'granted').length}/4 granted`} detail="Purpose-bound receipts" /><Metric label="Latest score" value={dynamicScore ? `${dynamicScore.dynamicScore} · ${dynamicScore.riskBand}` : 'Not requested'} detail="Higher is stronger reliability" /></div><Panel title="Workflow shortcuts" description="Move through the simulation in a deliberate order."><div className="grid gap-3 sm:grid-cols-3">{[['/app/consent','Consent','Set purpose boundaries'],['/app/score','Score','Review API evidence'],['/app/audit','Audit','Trace every event']].map(([href,label,detail]) => <Link className="rounded-md border border-border p-4 hover:bg-bg" key={href} to={href}><p className="font-medium text-ink">{label}</p><p className="mt-1 text-sm text-muted">{detail}</p></Link>)}</div></Panel></Page>;
}
